In [121]:
import pandas as pd
import seaborn as sns
import random
import numpy as np
import math
penguins = pd.read_csv('penguins.csv')

In [122]:
penguins.head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,FEMALE
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,MALE
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN

In [123]:
class ProcessingData:
    
    @staticmethod
    def shuffle(base):
        for x in range(len(base)-1,0,-1):
            newPlace = random.randint(0,x-1)
            base.loc[x],base.loc[newPlace]=base.loc[newPlace],base.loc[x]
            
    @staticmethod
    def normalize(base):
        base.iloc[:,2:-1] = (base.iloc[:,2:-1]-base.iloc[:,2:-1].min())/(base.iloc[:,2:-1].max()-base.iloc[:,2:-1].min())

    @staticmethod
    def devide(base):
        n = int(len(base)*0.7)
        base_tren = base[:n]
        base_valid = base[n:]
        return(base_tren,base_valid)

In [124]:
penguinsEdit = penguins.copy()

ProcessingData.shuffle(penguinsEdit)
ProcessingData.normalize(penguinsEdit)
trening_data,validate_data = ProcessingData.devide(penguinsEdit)

In [125]:
class Bayes:
    
    @staticmethod
    def recoverTreningData(data):
        sortedData = []
        sort = data.groupby(data.species)
        sortedData.append(sort.get_group("Adelie"))
        sortedData.append(sort.get_group("Chinstrap"))
        sortedData.append(sort.get_group("Gentoo"))

        return sortedData

    @staticmethod
    def meanMaker(sortedData):
        meanTable = []
        for j in range(len(sortedData)):
            meanTable.append(sortedData[j].mean(numeric_only=True).tolist())
        return meanTable

    @staticmethod
    def standardDeviation(sortedData,meanTable):
        deviationTable = []
        for j in range(len(sortedData)):
            deviationTable.append(sortedData[j].std(numeric_only=True).tolist())
        return deviationTable

    @staticmethod
    def gauss(validate_data,meanTable,deviationTable):
        correct = 0
        varieties = ["Adelie","Chinstrap","Gentoo"]
        for i in range(len(validate_data)):
            trueName = validate_data.iloc[i].species
            points = []
            for j in range(len(sortedData)):
                g = 1
                for k in range(2,len(sortedData[j].columns)-1):
                    g *= (1/(((2*math.pi)**(1/2))*deviationTable[j][k-2])*math.exp(-((validate_data.iloc[i][k]-meanTable[j][k-2])**2)/(2*(deviationTable[j][k-2])**2)))
                points.append(g)
            guessedName = varieties[np.argmax(points)]

            if guessedName == trueName:
                correct+=1
        return "Accuracy {:.2f}% => {}/{}".format(correct*100/len(validate_data),correct,len(validate_data))

In [126]:
sortedData = Bayes.recoverTreningData(trening_data)
meanTable = Bayes.meanMaker(sortedData)
deviationTable = Bayes.standardDeviation(sortedData,meanTable)
Bayes.gauss(validate_data,meanTable,deviationTable)

'Accuracy 96.15% => 100/104'