In [5]:
import pandas as pd
stragan = pd.read_csv('Straganik.csv')

In [6]:
stragan.head(15)

,swieze,mrozone,ostre,slodkie,zielone,czerwone,lokalne,tropikalne,lisciaste,bulwowe,nazwa
0,0.5,0.0,0.0,0.9,0.0,1.0,0.9,0.0,0.0,0.0,Jablko Czerwone
1,0.2,0.0,0.0,0.2,0.0,0.5,0.7,0.0,0.0,0.0,Marchewka
2,0.0,0.8,0.0,0.4,1.0,0.0,0.2,0.0,0.0,0.0,Groszek
3,0.8,0.0,0.0,0.2,0.1,0.2,0.5,0.0,0.0,1.0,Ziemniak
4,0.8,0.0,0.0,0.8,0.1,0.5,0.5,0.5,0.0,1.0,Batat
5,0.9,0.0,0.0,0.4,0.3,0.7,0.0,0.9,0.6,0.0,Rabarbar
6,0.5,0.0,0.0,0.9,1.0,0.0,0.9,0.0,0.0,0.0,Jablko Zielone
7,0.0,1.0,0.0,0.1,0.1,0.0,0.7,0.0,0.0,0.0,Pietruszka
8,0.8,0.0,0.0,0.2,0.7,0.0,0.8,0.0,0.0,0.0,Fasola
9,0.9,0.0,0.0,0.9,0.2,0.0,0.0,0.8,0.0,0.0,Banan
10,0.9,0.0,1.0,0.2,0.2,0.8,0.0,0.8,0.0,0.0,Papryczka chilli
11,0.8,0.0,0.0,1.0,0.5,0.5,0.0,1.0,0.0,0.0,Arbuz
12,0.6,0.0,0.0,0.6,0.8,0.0,0.0,1.0,0.0,0.0,Melon
13,0.9,0.0,0.0,0.7,0.0,1.0,0.0,1.0,0.0,0.0,Granat
14,0.8,0.0,0.0,0.1,1.0,0.0,1.0,0.0,1.0,0.0,Salata

In [9]:
def VegeFinder(item):
    data = []
    for row in range(len(stragan)):
        rowSum = 0
        for x in range(len(stragan.loc[row])-1):
            rowSum+=stragan.iloc[row,x]*item[x]
        data.append(round(rowSum,3))
    maxPoints = max(data)
    return stragan.at[data.index(maxPoints),"nazwa"]

Szukam = [0.9, 0.0, 0.0, 0.8, 0.8, 0.0, 0.0, 0.7, 0.0, 0.0]
VegeFinder(Szukam)

'Arbuz'